name: flutter_demo_app_jornaleros
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  camera: ^0.10.0+3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.7
  font_awesome_flutter: ^10.5.0
  get_it: ^7.2.0
  getwidget: ^4.0.0
  go_router: ^10.1.0
  google_mlkit_face_detection: ^0.4.0
  image: ^3.0.2
  locator: ^0.0.0-dev.2
  path: ^1.8.0
  path_provider: ^2.0.9
  shared_preferences: ^2.2.0
  sqflite: ^2.1.0+1
  tflite_flutter: ^0.9.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
